name: 'tests'

on: [pull_request]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: 'Checkout Project'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: yarn install --no-progress

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test

      - name: Generate production files
        run: yarn build
