name: NPM publish
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
jobs:
  build:
    name: 'npm publish'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: develop

      - name: 'Show current version'
        run: grep  '"version"' package.json

      # Setup .npmrc file to publish to npm
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          always-auth: true
          scope: '@openbeta'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm config set @openbeta https://registry.npmjs.org

      - run: echo ${{ secrets.NPM_TOKEN }} 

      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - run: cat ~/.npmrc

      - name: NPM publish
        run: yarn install --no-progress && yarn lint && yarn test && yarn build && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
